<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

echo "<!DOCTYPE html>\n";
echo "<html dir=\"ltr\" lang=\"fr-FR\">";
echo "<head>\n";

echo "<!--\n";
echo "Powered by 68koncept (www.68koncept.com)\n";
echo "-->";
echo "<meta charset=utf-8 />\n";
echo "<meta name=\"Keywords\" content=\"\" />\n";
echo "<meta name=\"Description\" content=\"\" />\n";
echo "<meta name=\"Author\" content=\"Aurelien LEQUOY\" />\n";
echo "<meta name=\"robots\" content=\"index,follow,all\" />\n";
echo "<meta name=\"generator\" content=\"GLIALE\" />\n";
echo "<meta name=\"runtime\" content=\"[PAGE_GENERATION]\" />\n";
echo "<link rel=\"shortcut icon\" href=\"favicon.ico\" />";
echo "<title>".strip_tags($this->title)." - PmaControl</title>\n";

echo "<!-- Fonts -->\n";
echo "<link rel=\"preconnect\" href=\"https://fonts.bunny.net\">\n";
echo "<link href=\"https://fonts.bunny.net/css?family=inter:400,500,600,700&display=swap\" rel=\"stylesheet\" />\n";

echo "<style>\n";
echo ":root {\n";
echo "    --color-primary: #007acc;\n";
echo "    --color-secondary: #6c757d;\n";
echo "    --color-accent: #28a745;\n";
echo "    --color-text: #212529;\n";
echo "    --color-text-muted: #6c757d;\n";
echo "    --color-bg: #ffffff;\n";
echo "    --color-bg-alt: #f8f9fa;\n";
echo "    --color-border: #dee2e6;\n";
echo "    --font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\n";
echo "}\n";
echo "\n";
echo "* {\n";
echo "    box-sizing: border-box;\n";
echo "}\n";
echo "\n";
echo "body {\n";
echo "    font-family: var(--font-family);\n";
echo "    color: var(--color-text);\n";
echo "    background-color: var(--color-bg);\n";
echo "    line-height: 1.6;\n";
echo "    margin: 0;\n";
echo "    padding: 0;\n";
echo "}\n";
echo "\n";
echo ".site-header {\n";
echo "    background-color: var(--color-bg);\n";
echo "    border-bottom: 1px solid var(--color-border);\n";
echo "    position: sticky;\n";
echo "    top: 0;\n";
echo "    z-index: 100;\n";
echo "}\n";
echo "\n";
echo ".nav-container {\n";
echo "    max-width: 1200px;\n";
echo "    margin: 0 auto;\n";
echo "    padding: 0 1rem;\n";
echo "}\n";
echo "\n";
echo ".nav-bar {\n";
echo "    display: flex;\n";
echo "    align-items: center;\n";
echo "    justify-content: space-between;\n";
echo "    padding: 1rem 0;\n";
echo "}\n";
echo "\n";
echo ".nav-logo {\n";
echo "    font-size: 1.5rem;\n";
echo "    font-weight: 700;\n";
echo "    color: var(--color-primary);\n";
echo "    text-decoration: none;\n";
echo "}\n";
echo "\n";
echo ".nav-menu {\n";
echo "    display: flex;\n";
echo "    align-items: center;\n";
echo "    gap: 2rem;\n";
echo "    margin: 0;\n";
echo "    padding: 0;\n";
echo "    list-style: none;\n";
echo "}\n";
echo "\n";
echo ".nav-menu .has-children {\n";
echo "    position: relative;\n";
echo "}\n";
echo "\n";
echo ".nav-menu a {\n";
echo "    text-decoration: none;\n";
echo "    color: var(--color-text);\n";
echo "    font-weight: 500;\n";
echo "    transition: color 0.2s;\n";
echo "    display: block;\n";
echo "    padding: 0.5rem 1rem;\n";
echo "}\n";
echo "\n";
echo ".nav-menu a:hover {\n";
echo "    color: var(--color-primary);\n";
echo "}\n";
echo "\n";
echo ".nav-menu .is-cta {\n";
echo "    background-color: var(--color-primary);\n";
echo "    color: white !important;\n";
echo "    border-radius: 6px;\n";
echo "    margin-left: 1rem;\n";
echo "}\n";
echo "\n";
echo ".nav-menu .is-cta:hover {\n";
echo "    background-color: #005ea3;\n";
echo "    color: white !important;\n";
echo "}\n";
echo "\n";
echo ".site-main {\n";
echo "    min-height: 60vh;\n";
echo "}\n";
echo "\n";
echo ".site-footer {\n";
echo "    background-color: #343a40;\n";
echo "    color: #adb5bd;\n";
echo "    padding: 3rem 0 2rem;\n";
echo "    margin-top: 4rem;\n";
echo "}\n";
echo "\n";
echo ".footer-container {\n";
echo "    max-width: 1200px;\n";
echo "    margin: 0 auto;\n";
echo "    padding: 0 1rem;\n";
echo "}\n";
echo "\n";
echo ".footer-grid {\n";
echo "    display: grid;\n";
echo "    grid-template-columns: 1fr;\n";
echo "    gap: 2rem;\n";
echo "}\n";
echo "\n";
echo ".footer-section h3 {\n";
echo "    color: white;\n";
echo "    margin-bottom: 1rem;\n";
echo "}\n";
echo "\n";
echo ".footer-section ul {\n";
echo "    list-style: none;\n";
echo "    padding: 0;\n";
echo "    margin: 0;\n";
echo "}\n";
echo "\n";
echo ".footer-section ul li {\n";
echo "    margin-bottom: 0.5rem;\n";
echo "}\n";
echo "\n";
echo ".footer-section ul li a {\n";
echo "    color: #adb5bd;\n";
echo "    text-decoration: none;\n";
echo "    transition: color 0.2s;\n";
echo "}\n";
echo "\n";
echo ".footer-section ul li a:hover {\n";
echo "    color: white;\n";
echo "}\n";
echo "\n";
echo ".footer-bottom {\n";
echo "    border-top: 1px solid #495057;\n";
echo "    margin-top: 2rem;\n";
echo "    padding-top: 1rem;\n";
echo "    text-align: center;\n";
echo "    color: #6c757d;\n";
echo "}\n";
echo "\n";
echo "/* Dropdown menu styles */\n";
echo ".dropdown {\n";
echo "    position: relative;\n";
echo "}\n";
echo "\n";
echo ".dropdown-content {\n";
echo "    display: none;\n";
echo "    position: absolute;\n";
echo "    background-color: white;\n";
echo "    min-width: 200px;\n";
echo "    box-shadow: 0 8px 16px rgba(0,0,0,0.1);\n";
echo "    border-radius: 6px;\n";
echo "    border: 1px solid var(--color-border);\n";
echo "    top: 100%;\n";
echo "    left: 0;\n";
echo "    z-index: 1000;\n";
echo "}\n";
echo "\n";
echo ".dropdown:hover .dropdown-content {\n";
echo "    display: block;\n";
echo "}\n";
echo "\n";
echo ".dropdown-content a {\n";
echo "    color: var(--color-text);\n";
echo "    padding: 0.75rem 1rem;\n";
echo "    text-decoration: none;\n";
echo "    display: block;\n";
echo "    border-radius: 0;\n";
echo "}\n";
echo "\n";
echo ".dropdown-content a:hover {\n";
echo "    background-color: var(--color-bg-alt);\n";
echo "    color: var(--color-primary);\n";
echo "}\n";
echo "\n";
echo ".dropdown-content a:first-child {\n";
echo "    border-radius: 6px 6px 0 0;\n";
echo "}\n";
echo "\n";
echo ".dropdown-content a:last-child {\n";
echo "    border-radius: 0 0 6px 6px;\n";
echo "}\n";
echo "\n";
echo "/* Language switcher */\n";
echo ".lang:lang(en) .lang-fr { display: none; }\n";
echo ".lang:lang(fr) .lang-en { display: none; }\n";
echo "\n";
echo "@media (max-width: 768px) {\n";
echo "    .nav-menu {\n";
echo "        flex-direction: column;\n";
echo "        position: absolute;\n";
echo "        top: 100%;\n";
echo "        left: 0;\n";
echo "        right: 0;\n";
echo "        background: white;\n";
echo "        border-top: 1px solid var(--color-border);\n";
echo "        gap: 0;\n";
echo "        box-shadow: 0 4px 8px rgba(0,0,0,0.1);\n";
echo "    }\n";
echo "\n";
echo "    .nav-menu.closed {\n";
echo "        display: none;\n";
echo "    }\n";
echo "}\n";
echo "</style>\n";
echo "</head>\n";
echo "<body class=\"lang lang-fr\">\n";
echo "    <header class=\"site-header\">\n";
echo "        <div class=\"nav-container\">\n";
echo "            <nav class=\"nav-bar\">\n";
echo "                <a href=\"/\" class=\"nav-logo\">PmaControl</a>\n";
echo "                <ul class=\"nav-menu\">\n";
echo "                    <!-- Menu will be populated by controller -->\n";
echo "                </ul>\n";
echo "            </nav>\n";
echo "        </div>\n";
echo "    </header>\n";
echo "\n";
echo "    <main class=\"site-main\">\n";
echo "    <?php echo \$this->html ?? ''; ?>\n";
echo "    </main>\n";
echo "\n";
echo "    <footer class=\"site-footer\">\n";
echo "        <div class=\"footer-container\">\n";
echo "            <div class=\"footer-grid\">\n";
echo "                <section class=\"footer-section\">\n";
echo "                    <h3>PmaControl</h3>\n";
echo "                    <p>Observabilité SQL augmentée</p>\n";
echo "                    <p>support@pmacontrol.com</p>\n";
echo "                    <p>&copy; 2025 PmaControl. All rights reserved.</p>\n";
echo "                </section>\n";
echo "\n";
echo "                <section class=\"footer-section\">\n";
echo "                    <h3>Support</h3>\n";
echo "                    <ul>\n";
echo "                        <li><a href=\"/site/documentation/\">Documentation</a></li>\n";
echo "                        <li><a href=\"/site/faq/\">FAQ</a></li>\n";
echo "                        <li><a href=\"/site/support/\">Centre de support</a></li>\n";
echo "                        <li><a href=\"/site/contact/\">Contact</a></li>\n";
echo "                    </ul>\n";
echo "                </section>\n";
echo "            </div>\n";
echo "\n";
echo "            <div class=\"footer-bottom\">\n";
echo "                <p>Site conçu avec ❤️ pour les bases de données MySQL / MariaDB</p>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </footer>\n";
echo "</body>\n";
echo "</html>\n";
?>
