set log_bin_trust_function_creators = 1;

DROP FUNCTION IF EXISTS ANY_VALUE;
DELIMITER //
CREATE AGGREGATE FUNCTION ANY_VALUE (x LONGBLOB) RETURNS LONGBLOB
BEGIN
 LOOP
  FETCH GROUP NEXT ROW;
  RETURN x;
 END LOOP; 
END //
DELIMITER ;