<?php

declare(strict_types=1);

use PHPUnit\Framework\TestCase;

/**
 * Issue #1190 — pin the wiring of the editable binlog_row_image picker
 * on the slave/show Durability card.
 */
final class SlaveShowBinlogRowImagePickerTest extends TestCase
{
    private string $view;
    private string $controller;

    protected function setUp(): void
    {
        $v = file_get_contents(__DIR__ . '/../../App/view/Slave/show.view.php');
        $c = file_get_contents(__DIR__ . '/../../App/Controller/Slave.php');
        $this->assertNotFalse($v);
        $this->assertNotFalse($c);
        $this->view = $v;
        $this->controller = $c;
    }

    public function testControllerIssuesCsrfTokenForPicker(): void
    {
        $this->assertStringContainsString(
            "SLAVE_BINLOG_ROW_IMAGE_SET_CSRF_SCOPE = 'slave.binlog_row_image.set'",
            $this->controller,
            'CSRF scope constant must be defined'
        );
        $this->assertStringContainsString(
            "\$data['slave_binlog_row_image_set_csrf_token'] = Csrf::issueToken(\$_SESSION, self::SLAVE_BINLOG_ROW_IMAGE_SET_CSRF_SCOPE);",
            $this->controller,
            'Slave::show must issue the CSRF token for the picker'
        );
        $this->assertStringContainsString(
            "\$data['binlog_row_image_values'] = self::BINLOG_ROW_IMAGE_VALUES;",
            $this->controller,
            'controller must pass the allow-list to the view'
        );
    }

    public function testControllerSetterActionIsDefined(): void
    {
        // The legacy single-variable setter is preserved for
        // backward-compat (existing tests + a possible direct caller),
        // and the generic setReplicationVariable also handles it.
        $this->assertStringContainsString(
            'public function setBinlogRowImage($param)',
            $this->controller
        );
        $this->assertStringContainsString(
            'public function setReplicationVariable($param)',
            $this->controller,
            'generic setReplicationVariable must exist (handles binlog_row_image too)'
        );
        $this->assertStringContainsString('CsrfGuard::ensureOrFail', $this->controller);
        $this->assertStringContainsString(
            "SET GLOBAL binlog_row_image = '",
            $this->controller,
            'legacy binlog_row_image setter must still build the SET GLOBAL'
        );
    }

    public function testViewRendersPickerForBinlogRowImageAmongOtherEditableVars(): void
    {
        // Issue #1198 — picker is no longer hard-coded for
        // binlog_row_image; it is generated by the generic
        // renderEditableCell() helper for every variable in the
        // whitelist. binlog_row_image is one of them.
        $this->assertStringContainsString('sv-rv-edit', $this->view);
        $this->assertStringContainsString('sv-rv-picker', $this->view);
        $this->assertStringContainsString('sv-rv-picker-apply', $this->view);
        $this->assertStringContainsString('sv-rv-picker-cancel', $this->view);
        // The new generic endpoint is what the picker hits.
        $this->assertStringContainsString('slave/setReplicationVariable/', $this->view);
        // Whitelist must include binlog_row_image.
        $controller = file_get_contents(__DIR__ . '/../../App/Controller/Slave.php');
        $this->assertStringContainsString(
            "'binlog_row_image'                         => ['type' => 'enum'",
            $controller,
            'binlog_row_image must remain editable via the generic whitelist'
        );
    }

    public function testApplyButtonCarriesCsrfToken(): void
    {
        // Generic CSRF field/token plumbing.
        $this->assertStringContainsString(
            'data-csrf-field="<?= htmlspecialchars($rvCsrfField',
            $this->view
        );
        $this->assertStringContainsString(
            'data-csrf-token="<?= htmlspecialchars($rvCsrfToken',
            $this->view
        );
    }

    public function testJsConfirmsDowngradeFromFull(): void
    {
        // FULL → MINIMAL/NOBLOB breaks pt-table-checksum and CDC; the
        // double-confirm now lives in the RISKY_DOWNGRADES table
        // shared by all variables.
        $this->assertStringContainsString('binlog_row_image: function(prev, next)', $this->view);
        $this->assertStringContainsString("prev.toUpperCase() === 'FULL'", $this->view);
        $this->assertStringContainsString('pt-table-checksum', $this->view);
        $this->assertStringContainsString('CDC', $this->view);
        $this->assertStringContainsString('confirm(', $this->view);
    }

    public function testApplyFetchUsesSvParseJsonResponse(): void
    {
        $this->assertStringContainsString('.then(svParseJsonResponse)', $this->view);
    }

    public function testSuccessFlowGivesVisibleConfirmationBeforeReload(): void
    {
        // The Apply button flips green and shows "previous → applied"
        // before the reload, so the operator knows the SET GLOBAL took.
        $this->assertStringContainsString("(prev === applied ? 'No change' : (prev + ' → ' + applied))", $this->view);
        $this->assertStringContainsString("btn.style.background = '#16a34a'", $this->view);
        $this->assertStringContainsString('setTimeout(function()', $this->view);
        $this->assertStringContainsString('window.location.reload()', $this->view);
        $this->assertStringContainsString("fa-spinner fa-spin", $this->view);
        $this->assertStringContainsString("Saving", $this->view);
    }
}
